### ISSUE TITLE
Advice on using for influxdb-ruby docs?

### ISSUE THREAD

**Issue by dmke** [influxdata/influx-theme#15]
Hi,

I'm planning to rework the docs for the [Ruby client](https://github.com/influxdata/influxdb-ruby), and stumbled upon this repository.

Is it ok to use the (official/light) theme for this, and if so, how would I keep it up-to-date? Preferrably, I'd use a CDN, but I'm OK with copy-pasting the asset files into a seperate branch (i.e. gh-pages).

**Comment by toddboom** [comment]
@dmke That's probably a question that @alexpaxton and I should figure out. It's probably best to just copy the assets for now, but I'll work on getting some sort of a CDN strategy in place soon.

Would it make sense for the ruby-client docs to be a part of [docs.influxdata.com](http://docs.influxdata.com/)?

**Comment by dmke** [comment]
> [...] best to just copy the assets for now [...]

Cool. I assume the files in `docs/dist` are the ones I'm interested in?

> Would it make sense for the ruby-client docs to be a part of docs.influxdata.com?

Hm... Maybe?

In the near future, I'm going to do some rework on the client's API (ref. influxdata/influxdb-ruby#41 and influxdata/influxdb-ruby#152), so I will have to update the docs quite often (propably resulting in large PRs to influxdata/docs.influxdata.com).

**Comment by dmke** [comment]
I've found no time reworking the docs, so I'm closing this for now.
